### ISSUE TITLE
half-elided footnote number = can't use edit pencil on it

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#772] opened 2019-04-30 21:08 UTC
(this a bug on staging, noted while testing #745 )

if i elide only half of a footnote's 'call' (the footnote # that appears in the text), then click the edit pencil, it won't let me edit it -instead just sends me down the page to the footnote itself.

Partially elided footnote call:
![Screen Shot 2019-04-30 at 5 06 52 PM](https://user-images.githubusercontent.com/12850389/56993407-62cfc600-6b6a-11e9-8309-805c6ebd02b5.png)

example taken from: https://h2o-dev-test.lil.tools/casebooks/88629-constitutional-law-separation-of-powers-federalism-and-fourteenth-amendment-spring-2018/resources/1.1.3-nebbia-v-new-york/annotate

**Comment by rebeccacremona** [comment] 2019-05-01 01:56
I think we should fix this by causing a validation error if someone tries to elide half a footnote marker. Definitely not a supported behavior 😜

**Comment by holtchesley** [comment] 2020-02-24 21:17
Duplicate of https://github.com/harvard-lil/h2o/issues/765

**Closed by holtchesley** 2020-02-24 21:17 UTC
Labels: annotations, bug, footnotes
