### ISSUE TITLE
Eliding block quotes leaves blank lines and elided para numbers

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/h2o#838] opened 2019-07-29 17:51 UTC
When you elide text containing a block quote, H2O displays a blank line and the paragraph number, which is out of alignment with other paragraph numbers. Note this behavior is slightly different, but still buggy, on prod --> the blank lines still display but the paragraph numbers do not.

Elided text containing block quotes should have same appearance as any other elided text. 

Example on experiment: see paragraphs 71-85 - https://h2o-experiment.lil.tools/casebooks/79342-corporations/resources/2.1.2-blasius-industries-inc-v-atlas-corp-del-ch-1988#/

![image](https://user-images.githubusercontent.com/2140548/62069954-780ace00-b207-11e9-899b-8d82ed29de20.png)

Example on prod: see paragraphs 71-85 - https://opencasebook.org/casebooks/79342-corporations/resources/2.1.2-blasius-industries-inc-v-atlas-corp-del-ch-1988#/

![image](https://user-images.githubusercontent.com/2140548/62070134-e2bc0980-b207-11e9-8525-4bcaf3f6ad33.png)

**Comment by leppert** [comment] 2019-07-29 18:02
This is the result of padding being applied to blockquotes — the reason for the paragraph number difference is that the new branch depends on elided paragraphs collapsing to 0 height in order to “hide” the numbers; this allows the logic for enumerating and hiding paragraph numbers to exist entirely within the CSS. All that to say, fixing the padding on blockquotes should fix this in both instances. I’ll give it a look when I have a chance unless someone beats me to it.

**Comment by rebeccacremona** [comment] 2019-07-30 20:57
@leppert It's worth nothing that this technique does not hide the "hidden" paragraph numbers from screenreader users. For instance, in this bit of that case, on experiment:
![image](https://user-images.githubusercontent.com/11020492/62164536-95649880-b2ea-11e9-992f-f2955c22fc1d.png)
"heading, level two, DAMAGES. elided text, collapsed button. 43 44 45. 46 urt will not....". That could be fine, but is a little weird.

**Comment by leppert** [comment] 2019-07-30 22:49
Ah! Glad you found that. I’ll have to think about whether this is solvable with the CSS based scheme I have here. It greatly simplified the template logic but it does seem we should work to prevent regression in accessibility.

**Comment by holtchesley** [comment] 2020-02-14 14:26
Addressed in #1075 .

**Closed by holtchesley** 2020-02-14 14:26 UTC
Labels: annotations
