### ISSUE TITLE
Something in text causing Word unable to open export

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#621] opened 2018-12-11 23:57 UTC
Two examples of failure:

https://opencasebook.org/casebooks/110237-open-property-brett-clone-for-bug-testing/resources/1.8.4-the-defeasible-fees/annotate

https://opencasebook.org/casebooks/110237-open-property-brett-clone-for-bug-testing/resources/1.8.5-remainders-part-4-divestment-of-future-interests-types-of-vested-remainders/annotate

Both can be exported, but give the below errors when attempting to open in word:
![screen shot 2018-12-11 at 6 57 06 pm](https://user-images.githubusercontent.com/12850389/49837963-9b673280-fd76-11e8-8ea1-506e81c80ded.png)
![screen shot 2018-12-11 at 6 56 59 pm](https://user-images.githubusercontent.com/12850389/49837964-9b673280-fd76-11e8-91d9-ef94f1347299.png)

Both contain text that was pasted into H2O.

**Comment by bjohnson747** [comment] 2018-12-12 00:05
In separate testing - not on these items, which i've preserved - when I 
(1) removed both the footnote links and the line-break (not sure what it is called, it shows up as a red-dotted line in the editor when i put my mouse over it) that's next to the footnotes, and 
(2) pasted it into Text Edit, then pasted it back into H2O, 
it export successfully.

**Comment by cgruppioni** [comment] 2019-05-20 16:56
Dupe of #640

**Closed by cgruppioni** 2019-05-20 16:56 UTC
Labels: bug, export
