### ISSUE TITLE
misc extra characters in export file, not in H2O version

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/h2o#670] opened 2019-02-13 17:37 UTC
Example from this case: https://opencasebook.org/casebooks/114149-advanced-constitutional-law/resources/5.1.1-jane-doe-no-1-et-al-plaintiffs-appellants-v-backpage-com-llc-et-al-defendants-appellees#

The word "outrage" shows up fine on the H2O side, 
<img width="352" alt="screen shot 2019-02-13 at 12 34 40 pm" src="https://user-images.githubusercontent.com/12850389/52731582-0a862080-2f8c-11e9-8c84-9da970d8f8ce.png">
but when exporting this resource (or full casebook) it appears as "out-rage"
<img width="335" alt="screen shot 2019-02-13 at 12 35 14 pm" src="https://user-images.githubusercontent.com/12850389/52731587-0d811100-2f8c-11e9-96fb-d4a5c98acec9.png">

There are other examples in the export with hyphens (or double hyphens) in words, or an added comma,

**Comment by leppert** [comment] 2019-02-13 18:08
@bjohnson747 @cgruppioni Looks like that section has [soft hyphens](https://en.wikipedia.org/wiki/Soft_hyphen) in it (see the blue characters in the screenshot). Probably has something to do with the way the xslt is transforming the text for Word.
![image](https://user-images.githubusercontent.com/26643/52732934-71f19f80-2f8f-11e9-80a0-6927738eb507.jpeg)

**Comment by abziegler** [comment] 2019-03-01 18:11
@bjohnson747 @cgruppioni at least in this example, looks like the soft hyphens are encoded into the text in H2O (I confirmed by looking at source in Rails admin). So it's not being introduced into the export during export process. It appears the case was ingested via CAP, b/c there are some OCR artifacts, but I don't see these soft hyphens in any of the CAP formats.

**Comment by abziegler** [comment] 2019-03-06 14:53
My last comment was wrong. The soft hyphens are coming from CAP HTML format. So we're bringing them in from CAP; suppressing them in our case templates; and not suppressing them in our export template.

**Comment by leppert** [comment] 2019-03-06 15:06
@abziegler They're not so much suppressed in the case templates as they're rendered per their intended use. From the soft hyphen [wikipedia entry](https://en.wikipedia.org/wiki/Soft_hyphen):

> It serves as an invisible marker used to specify a place in text where a hyphenated break is allowed without forcing a line break in an inconvenient place if the text is re-flowed.

So, in the exports, rather than optionally displaying a hyphen where needed (as the browser does at its own discretion in case templates), a regular hyphen is being displayed at every instance of a soft hyphen.

**Comment by abziegler** [comment] 2019-03-06 15:11
Cool. So we'll have to investigate how to make the exports not do that? :)

**Comment by leppert** [comment] 2019-03-06 15:22
Yes exactly. I think you could write a matcher in the xslt files that just removes them entirely, but I think the better option (time permitting) would be to see if Word supports soft hyphen and whether there's a way to leave them in and have them behave as expected; they're there for typesetting hinting and it'll certainly improve the layout if they can remain.

**Comment by rebeccacremona** [comment] 2019-05-03 22:48
docx docs (ba dum chhh) reveal that Word does support hard and soft hyphens: http://officeopenxml.com/WPtextSpecialContent.php

so, pending more research into where to handle the translation, I'm optimistic we can make this work.

**Comment by leppert** [comment] 2019-05-12 18:09
@jcushman says that soft hyphens have been removed from the CAPAPI renders, so these shouldn't show up for cases that are ingested in the future, though they'll remain in whatever cases have already been ingested into H2O. Regardless, this bug should probably still get sorted.

**Comment by rebeccacremona** [comment] 2019-11-19 15:51
Fixed via pandoc export.

**Closed by rebeccacremona** 2019-11-19 15:51 UTC
Labels: bug, capapi, export, pandoc
