### ISSUE TITLE
Firefox: Eliding below an expanded elision causes incorrect offset

### ISSUE THREAD

**Issue by leppert** [harvard-lil/h2o#609] opened 2018-12-03 18:30 UTC
When an elision in a paragraph is expanded and a new elision is created below it, within the same paragraph, the new elision will be placed incorrectly. This appears to only happen in Firefox.

http://recordit.co/s2TTqcAZkK

**Comment by holtchesley** [comment] 2020-02-19 16:25
This appears to have been resolved in the last ~year, I'm unable to reproduce this now.

**Closed by holtchesley** 2020-02-19 16:25 UTC
Labels: Browser specific, annotations
